In [1]:
import pandas as pd
import sklearn
from sklearn.model_selection import train_test_split
from sklearn import preprocessing as ppr
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

In [2]:
#Loading the iris data

iris = pd.read_csv("D:\IISER-B\Iris_flower_detection\iris_cleaned.csv")
iris = iris.drop(columns=['Unnamed: 0'])
iris

<>:3: SyntaxWarning: invalid escape sequence '\I'
<>:3: SyntaxWarning: invalid escape sequence '\I'
C:\Users\Nirman\AppData\Local\Temp\ipykernel_20308\903039002.py:3: SyntaxWarning: invalid escape sequence '\I'
  iris = pd.read_csv("D:\IISER-B\Iris_flower_detection\iris_cleaned.csv")


sepal_length  sepal_width  petal_length  petal_width           class
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
141           6.7          3.0           5.2          2.3  Iris-virginica
142           6.3          2.5           5.0          1.9  Iris-virginica
143           6.5          3.0           5.2          2.0  Iris-virginica
144           6.2          3.4           5.4          2.3  Iris-virginica
145           5.9          3.0           5.1          1.8  Iris-virginica

[146 rows x 5 columns]

train test split

In [3]:
features = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width']
target = ['class']
X,x_test,Y,y_test = train_test_split(iris[features],iris[target],test_size=0.3,random_state=100)


encoding target variable

In [4]:
lab_en = ppr.LabelEncoder()
Y = lab_en.fit_transform(Y)
y_test = lab_en.fit_transform(y_test)
y_test

c:\Users\Nirman\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\preprocessing\_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Users\Nirman\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\preprocessing\_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([1, 0, 0, 0, 0, 2, 1, 2, 0, 2, 0, 0, 1, 0, 2, 2, 1, 0, 0, 2, 1, 1,
       0, 2, 2, 1, 2, 1, 2, 1, 2, 2, 2, 1, 1, 0, 0, 0, 0, 0, 0, 2, 2, 2])

applying knn classier using pipeline

In [5]:

pipe = Pipeline([('std', StandardScaler()), ('knn', KNeighborsClassifier())], 
                verbose = True)
pipe.fit(X,Y)
param_grid = {
    'knn__n_neighbors': [3, 5, 7, 9],      # Tuning the number of neighbors
    'knn__weights': ['uniform', 'distance'], # Weighting options
    'knn__metric': ['euclidean', 'manhattan'] # Distance metrics
}
gs_knn = GridSearchCV(pipe, param_grid, cv=5, scoring='accuracy')
gs_knn.fit(X, Y)




[Pipeline] ............... (step 1 of 2) Processing std, total=   0.0s
[Pipeline] ............... (step 2 of 2) Processing knn, total=   0.0s
[Pipeline] ............... (step 1 of 2) Processing std, total=   0.0s
[Pipeline] ............... (step 2 of 2) Processing knn, total=   0.0s
[Pipeline] ............... (step 1 of 2) Processing std, total=   0.0s
[Pipeline] ............... (step 2 of 2) Processing knn, total=   0.0s
[Pipeline] ............... (step 1 of 2) Processing std, total=   0.0s
[Pipeline] ............... (step 2 of 2) Processing knn, total=   0.0s
[Pipeline] ............... (step 1 of 2) Processing std, total=   0.0s
[Pipeline] ............... (step 2 of 2) Processing knn, total=   0.0s
[Pipeline] ............... (step 1 of 2) Processing std, total=   0.0s
[Pipeline] ............... (step 2 of 2) Processing knn, total=   0.0s
[Pipeline] ............... (step 1 of 2) Processing std, total=   0.0s
[Pipeline] ............... (step 2 of 2) Processing knn, total=   0.0s
[Pipel

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('std', StandardScaler()),
                                       ('knn', KNeighborsClassifier())],
                                verbose=True),
             param_grid={'knn__metric': ['euclidean', 'manhattan'],
                         'knn__n_neighbors': [3, 5, 7, 9],
                         'knn__weights': ['uniform', 'distance']},
             scoring='accuracy')

In [16]:
print(gs_knn.best_params_)


{'knn__metric': 'euclidean', 'knn__n_neighbors': 9, 'knn__weights': 'distance'}


In [6]:
from sklearn.metrics import classification_report
y_pred = gs_knn.predict(x_test)
from sklearn.metrics import confusion_matrix
print("Confusion Matrix\n\n",confusion_matrix(y_test,y_pred))
print("Classification Report:")
print(classification_report(y_test, y_pred))

Confusion Matrix

 [[17  0  0]
 [ 0 11  0]
 [ 0  0 16]]
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        17
           1       1.00      1.00      1.00        11
           2       1.00      1.00      1.00        16

    accuracy                           1.00        44
   macro avg       1.00      1.00      1.00        44
weighted avg       1.00      1.00      1.00        44



applying random forest

In [7]:
from sklearn.ensemble import RandomForestClassifier

In [8]:
rf = RandomForestClassifier(n_estimators=100, random_state=42)
rf.fit(X,Y)
param_grid = {
    'n_estimators': [50, 100, 200],
    'max_depth': [None, 10, 20, 30],
    'max_features': ['sqrt', 'log2'],
    'min_samples_split': [2, 5, 10]
}
gs_rf = GridSearchCV(estimator=rf, param_grid=param_grid, 
                     cv=5, scoring='accuracy')
gs_rf.fit(X, Y)


GridSearchCV(cv=5, estimator=RandomForestClassifier(random_state=42),
             param_grid={'max_depth': [None, 10, 20, 30],
                         'max_features': ['sqrt', 'log2'],
                         'min_samples_split': [2, 5, 10],
                         'n_estimators': [50, 100, 200]},
             scoring='accuracy')

In [9]:

y_pred = gs_rf.predict(x_test)
print("Confusion Matrix\n\n",confusion_matrix(y_test,y_pred))
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

Confusion Matrix

 [[17  0  0]
 [ 0 10  1]
 [ 0  0 16]]

Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        17
           1       1.00      0.91      0.95        11
           2       0.94      1.00      0.97        16

    accuracy                           0.98        44
   macro avg       0.98      0.97      0.97        44
weighted avg       0.98      0.98      0.98        44



applying AdaBoost Classifier

In [10]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier

In [11]:
base_estimator = DecisionTreeClassifier(max_depth=1)  # Weak learner
ada = AdaBoostClassifier(base_estimator, n_estimators=50, learning_rate=1.0, 
                         random_state=100)
ada.fit(X, Y)


c:\Users\Nirman\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(


AdaBoostClassifier(estimator=DecisionTreeClassifier(max_depth=1),
                   random_state=100)

In [12]:
param_grid = {
    'n_estimators': [50, 100, 200],
    'learning_rate': [0.01, 0.1, 1.0]
}
gs_ada = GridSearchCV(estimator=ada, param_grid=param_grid, cv=5, 
                      scoring='accuracy')
gs_ada.fit(X,Y)
y_pred = gs_ada.predict(x_test)
print("Confusion Matrix\n\n",confusion_matrix(y_test,y_pred))
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

c:\Users\Nirman\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Nirman\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Nirman\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
c:\Users\Nirman\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default)

Confusion Matrix

 [[17  0  0]
 [ 0 10  1]
 [ 0  0 16]]

Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        17
           1       1.00      0.91      0.95        11
           2       0.94      1.00      0.97        16

    accuracy                           0.98        44
   macro avg       0.98      0.97      0.97        44
weighted avg       0.98      0.98      0.98        44



In [13]:

features = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width']
for i in range(0,3):
    for j in range(1,4):
        x_updated = X[[features[i],features[j]]]
        xtest_updated = x_test[[features[i],features[j]]]
        pipe = Pipeline([('std', StandardScaler()), ('knn', KNeighborsClassifier())], 
                verbose = True)
        pipe.fit(x_updated,Y)
        y_pred = pipe.predict(xtest_updated)
        print(features[i],features[j])
        print("Confusion Matrix\n\n",confusion_matrix(y_test,y_pred))
        print("Classification Report:")
        print(classification_report(y_test, y_pred))


        


[Pipeline] ............... (step 1 of 2) Processing std, total=   0.0s
[Pipeline] ............... (step 2 of 2) Processing knn, total=   0.0s
sepal_length sepal_width
Confusion Matrix

 [[17  0  0]
 [ 0  8  3]
 [ 0  6 10]]
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        17
           1       0.57      0.73      0.64        11
           2       0.77      0.62      0.69        16

    accuracy                           0.80        44
   macro avg       0.78      0.78      0.78        44
weighted avg       0.81      0.80      0.80        44

[Pipeline] ............... (step 1 of 2) Processing std, total=   0.0s
[Pipeline] ............... (step 2 of 2) Processing knn, total=   0.0s
sepal_length petal_length
Confusion Matrix

 [[17  0  0]
 [ 0 10  1]
 [ 0  0 16]]
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        17
           1     